import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import '@mantine/core/styles.css'
import './globals.css'

import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from "@mantine/core";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className='h-full'
            {...mantineHtmlProps}
        >
        <head>
            <ColorSchemeScript/>
            <title>Task Flow</title>
        </head>
        <body className="min-h-full flex flex-col">
        <MantineProvider>
            {children}
        </MantineProvider>
        </body>
        </html>
    );
}
